# Basic Information 
title: Zhicheng Huang
position: Masters Student
affiliation: Brown University
# subaffiliation: Spin-Ion Technologies 
affiliation_link: https://www.brown.edu/
# subaffiliation_link: https://www.spin-ion.com/
# affiliation_logo: ./assets/img/spinion.svg
email: zhicheng_huang (at) brown.edu
email2: zhicheng.huang1999 (at) gmail.com
location: Providence, RI, USA

# Search Engine Optimization (SEO)
keywords: zhicheng huang, huang zhicheng, zhichenghuang, huangzhicheng
canonical: https://minimal-light-theme.yliu.me/
description: Zhicheng Huang is currently a second-year student in the Sc.M. of Computer Science program at Brown University, working with the ATLAS Group under the mentorship of Nikos Vasilakis and the Brown HCI Group under the mentoshipt of Jeff Huang. Previously, he received the B.S. degree in Computer Science and Cognitive Science from the University of Michigan, Ann Arbor. Instead of relying on centralized platforms to manage users' data, He believes in an information ecology where users could easily (1) Access, (2) Manage, (3) Make Sense Of, and (4) Process their own data. Moreover, the tools people use to achieve this ecosystem should be user-centric, require zero to minimal programming, and contribute to the overall conviviality.



# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
# cv_link: https://blog.songchen.science/de3ec0aa2234aa1e3ee275bbc715c6c9/CV.pdf
google_scholar: https://scholar.google.com/citations?user=_msJ5AcAAAAJ&hl=en
# github_link: https://github.com/song-chen1/
linkedin: https://www.linkedin.com/in/zhichenghuang/
# researchgate: https://www.researchgate.net/profile/Song-Chen-60

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light


# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one




# The following files will be removed from the generated website.
exclude:
  - vendor
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
